"""empty message

Revision ID: 13a754582085
Revises: d32143bca838
Create Date: 2024-08-02 09:47:26.061585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a754582085'
down_revision = 'd32143bca838'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'incorrect_answer_text')
    op.drop_column('levels', 'correct_answer_message')
    op.drop_column('levels', 'reward')
    op.add_column('questions', sa.Column('reward', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'reward')
    op.add_column('levels', sa.Column('reward', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('levels', sa.Column('correct_answer_message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('levels', sa.Column('incorrect_answer_text', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
