"""empty message

Revision ID: 2a2e15e81d4f
Revises: 13a754582085
Create Date: 2024-08-02 09:59:56.138874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2e15e81d4f'
down_revision = '13a754582085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('questions', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'image_data')
    op.drop_column('levels', 'image_data')
    # ### end Alembic commands ###
