"""empty message

Revision ID: 2d50c9aeaf53
Revises: 8579bca51388
Create Date: 2024-08-01 12:13:02.592085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d50c9aeaf53'
down_revision = '8579bca51388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('correct_answer_message', sa.Text(), nullable=True))
    op.add_column('levels', sa.Column('reward', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'reward')
    op.drop_column('levels', 'correct_answer_message')
    # ### end Alembic commands ###
