"""empty message

Revision ID: 32cc23959ecb
Revises: ce81c46b38af
Create Date: 2024-08-04 13:07:15.628455

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = '32cc23959ecb'
down_revision = 'ce81c46b38af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('is_intro', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'is_intro')
    # ### end Alembic commands ###
