"""empty message

Revision ID: 357334ff273a
Revises: 2d50c9aeaf53
Create Date: 2024-08-01 12:15:56.654749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357334ff273a'
down_revision = '2d50c9aeaf53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'correct_answer_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('levels', 'reward',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'reward',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('levels', 'correct_answer_message',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
