"""empty message

Revision ID: 3d330b607ae0
Revises: fd65d07847c6
Create Date: 2024-08-04 13:16:22.885653

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = '3d330b607ae0'
down_revision = 'fd65d07847c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'intro_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'intro_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
