"""add admin flag

Revision ID: 3ed2dfbec898
Revises: 215546eb5a32
Create Date: 2024-09-03 22:07:46.304271

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = '3ed2dfbec898'
down_revision = '215546eb5a32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET admin = FALSE")
    op.alter_column('users', 'admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
