"""empty message

Revision ID: 4b3f8c5470ee
Revises: 3d330b607ae0
Create Date: 2024-08-04 13:56:25.518981

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b3f8c5470ee'
down_revision = '3d330b607ae0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_states')
    # ### end Alembic commands ###
