"""empty message

Revision ID: 66e74d650591
Revises: 5dc6b7ae480c
Create Date: 2024-08-04 07:56:20.637925

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = '66e74d650591'
down_revision = '5dc6b7ae480c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'levels', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'levels', type_='unique')
    op.alter_column('levels', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
