"""empty message

Revision ID: 8579bca51388
Revises: aa83ace062c7
Create Date: 2024-08-01 12:09:18.199483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8579bca51388'
down_revision = 'aa83ace062c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('intro_text', sa.Text(), nullable=False),
    sa.Column('incorrect_answer_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_levels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'level_id', 'id')
    )
    op.create_table('user_skipped_levels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'level_id', 'id')
    )
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('questions', sa.Column('level_id', sa.UUID(), nullable=False))
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=False))
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('questions', 'hint',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_foreign_key(None, 'questions', 'levels', ['level_id'], ['id'])
    op.drop_column('questions', 'stage_id')
    op.drop_column('questions', 'reward')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('chat_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('current_level', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'users', ['chat_id'])
    op.create_foreign_key(None, 'users', 'levels', ['current_level'], ['id'])
    op.drop_column('users', 'current_stage')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('current_stage', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'balance')
    op.drop_column('users', 'current_level')
    op.drop_column('users', 'chat_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('questions', sa.Column('reward', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('stage_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.alter_column('questions', 'hint',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'level_id')
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('user_skipped_levels')
    op.drop_table('user_levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
