"""empty message

Revision ID: 9376c5e63130
Revises: e8854c509a84
Create Date: 2024-08-04 09:31:15.264158

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9376c5e63130'
down_revision = 'e8854c509a84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stages_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stages_completed')
    # ### end Alembic commands ###
