"""empty message

Revision ID: aa26cf8aaee1
Revises: b50340baf4e1
Create Date: 2024-08-18 14:13:12.431862

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = 'aa26cf8aaee1'
down_revision = 'b50340baf4e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'is_object_recognition',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint('uq_user_skipped_levels_user_id_stage_id', 'stage_completions', ['user_id', 'stage_id'])
    op.create_unique_constraint('uq_user_levels_user_id_level_id', 'user_levels', ['user_id', 'level_id'])
    op.create_unique_constraint('uq_user_skipped_levels_user_id_level_id', 'user_skipped_levels', ['user_id', 'level_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skipped_levels_user_id_level_id', 'user_skipped_levels', type_='unique')
    op.drop_constraint('uq_user_levels_user_id_level_id', 'user_levels', type_='unique')
    op.drop_constraint('uq_user_skipped_levels_user_id_stage_id', 'stage_completions', type_='unique')
    op.alter_column('levels', 'is_object_recognition',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
