"""empty message

Revision ID: b50340baf4e1
Revises: dd17277b109b
Create Date: 2024-08-10 18:21:39.457203

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = 'b50340baf4e1'
down_revision = 'dd17277b109b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('is_object_recognition', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'is_object_recognition')
    # ### end Alembic commands ###
