"""empty message

Revision ID: c853afc4aabc
Revises: aa26cf8aaee1
Create Date: 2024-08-18 16:08:17.097328

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = 'c853afc4aabc'
down_revision = 'aa26cf8aaee1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_levels', sa.Column('is_skipped', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_levels', 'is_skipped')
    # ### end Alembic commands ###
