"""empty message

Revision ID: ce81c46b38af
Revises: 9376c5e63130
Create Date: 2024-08-04 09:37:11.501764

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce81c46b38af'
down_revision = '9376c5e63130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stages_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stages_completed', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
