"""empty message

Revision ID: d7aff0f7d8c1
Revises: f2e99912154f
Create Date: 2024-08-04 14:02:26.143680

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = 'd7aff0f7d8c1'
down_revision = 'f2e99912154f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_states_user_id', 'user_states', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_states_user_id', 'user_states', type_='unique')
    # ### end Alembic commands ###
