"""empty message

Revision ID: dd17277b109b
Revises: f914c188678d
Create Date: 2024-08-10 17:42:36.680162

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = 'dd17277b109b'
down_revision = 'f914c188678d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('is_info_collection', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'position')
    op.drop_column('users', 'company')
    op.drop_column('levels', 'is_info_collection')
    # ### end Alembic commands ###
