"""empty message

Revision ID: e8854c509a84
Revises: 66e74d650591
Create Date: 2024-08-04 09:15:11.393922

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = 'e8854c509a84'
down_revision = '66e74d650591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('reward', sa.Integer(), nullable=True))
    op.drop_column('questions', 'reward')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('reward', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('levels', 'reward')
    # ### end Alembic commands ###
