"""empty message

Revision ID: f2e99912154f
Revises: 4b3f8c5470ee
Create Date: 2024-08-04 14:01:09.466357

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = 'f2e99912154f'
down_revision = '4b3f8c5470ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
