"""empty message

Revision ID: fd65d07847c6
Revises: 32cc23959ecb
Create Date: 2024-08-04 13:10:52.635093

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType


# revision identifiers, used by Alembic.
revision = 'fd65d07847c6'
down_revision = '32cc23959ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('levels', 'intro_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('levels', 'is_intro',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('questions', 'hint',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'hint',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('levels', 'is_intro',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('levels', 'intro_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('levels', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
