"""empty message

Revision ID: fd7d8259aa0f
Revises: 2a2e15e81d4f
Create Date: 2024-08-02 10:19:55.377399

"""
from alembic import op
import sqlalchemy as sa
from src.database.custom_types import FileType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd7d8259aa0f'
down_revision = '2a2e15e81d4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('image_file', FileType(), nullable=True))
    op.drop_column('levels', 'image_data')
    op.add_column('questions', sa.Column('image_file', FileType(), nullable=True))
    op.drop_column('questions', 'image_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'image_file')
    op.add_column('levels', sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('levels', 'image_file')
    # ### end Alembic commands ###
